<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Service Results PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            color: #333;
            border-bottom: 2px solid #ccc;
            padding-bottom: 5px;
        }
        .service-block {
            margin-bottom: 30px;
            padding: 15px;
            border: 1px solid #ddd;
            background-color: #f9f9f9;
        }
        .service-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
            text-transform: capitalize;
            color: #444;
        }
        .service-meta {
            font-size: 12px;
            color: #777;
            margin-bottom: 15px;
        }
        .service-content {
            font-size: 14px;
            line-height: 1.6;
            white-space: pre-wrap;
            word-wrap: break-word;
        }
        .footer {
            margin-top: 50px;
            font-size: 12px;
            text-align: center;
            color: #999;
        }
    </style>
</head>
<body>
    <h1>Processing Results</h1>
    <p><strong>File Name:</strong> <?php echo e($fileName ?? 'Unknown'); ?></p>
    <p><strong>Generated At:</strong> <?php echo e(\Carbon\Carbon::now()->toDateTimeString()); ?></p>

    <hr>

    <?php if($services && count($services) > 0): ?>
        <?php $__currentLoopData = $services; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $service): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <div class="service-block">
                <div class="service-title">
                    <?php echo e($service->type); ?> Service
                    <?php if($service->type === 'translation' && $service->target_language): ?>
                        (<?php echo e($service->target_language); ?>)
                    <?php endif; ?>
                </div>
                <div class="service-meta">
                    Status: <?php echo e(ucfirst($service->status)); ?> | 
                    Completed: <?php echo e($service->completed_at ? $service->completed_at->toDateTimeString() : 'Pending'); ?>

                </div>
                
                <div class="service-content">
                    <?php if($service->status === 'completed' && $service->output): ?>
                        <?php if($service->type === 'ocr'): ?>
                            <?php echo e($service->output['text'] ?? 'No text output.'); ?>

                        <?php elseif($service->type === 'summarization'): ?>
                            <?php echo e($service->output['summary'] ?? 'No summary output.'); ?>

                        <?php elseif($service->type === 'translation'): ?>
                            <?php echo e($service->output['translated_text'] ?? 'No translation output.'); ?>

                        <?php else: ?>
                            <?php echo e(json_encode($service->output, JSON_PRETTY_PRINT)); ?>

                        <?php endif; ?>
                    <?php else: ?>
                        <em>Processing is not complete or no output is available.</em>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
    <?php else: ?>
        <p>No service results found.</p>
    <?php endif; ?>

    <div class="footer">
        Generated by AI-Powered PDF Processor
    </div>
</body>
</html>
<?php /**PATH E:\AI-Powered-pdf-Processer\ai-pdf-laravel\resources\views/pdf/service_results.blade.php ENDPATH**/ ?>